# Generated by Django 2.0.7 on 2020-05-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField(null=True)),
                ('summary', models.TextField(blank=True)),
                ('feature', models.BooleanField()),
                ('feature2', models.BooleanField(default=True)),
            ],
        ),
    ]
