# Generated by Django 2.0.7 on 2020-05-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='AppOne',
        ),
    ]
