# Generated by Django 2.0.7 on 2020-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appone',
            name='summary',
            field=models.TextField(),
        ),
    ]
